from __future__ import annotations
from typing import Any, Protocol
from .models import Customer, Conversation

class CustomerRepository(Protocol):
    async def save(self, customer: Customer) -> Customer: ...
    async def get(self, customer_id: str) -> Customer | None: ...

class ConversationRepository(Protocol):
    async def save(self, conversation: Conversation) -> Conversation: ...
    async def get(self, conversation_id: str) -> Conversation | None: ...

class CustomerIdentityResolver(Protocol):
    async def resolve(self, email: str | None, external_id: str | None) -> dict[str, Any] | None: ...
