"use client";
import { useEffect, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Header } from "@/components/layout/header";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { listInboxConversations, setConversationHandoff, getInboxMessages, sendInboxMessage } from "@/lib/api";
import { MessageCircle, UserRound, Send } from "lucide-react";
export default function InboxPage(){
 const qc=useQueryClient(); const [selected,setSelected]=useState<string|null>(null); const [text,setText]=useState("");
 const q=useQuery({queryKey:["inbox"],queryFn:listInboxConversations,refetchInterval:10000});
 const activeId=selected ?? q.data?.[0]?.id ?? null;
 const messages=useQuery({queryKey:["inbox-messages",activeId],queryFn:()=>getInboxMessages(activeId!),enabled:!!activeId,refetchInterval:4000});
 const handoff=useMutation({mutationFn:(x:{id:string;requested:boolean})=>setConversationHandoff(x.id,x.requested),onSuccess:()=>qc.invalidateQueries({queryKey:["inbox"]})});
 const send=useMutation({mutationFn:()=>sendInboxMessage(activeId!,text),onSuccess:()=>{setText("");messages.refetch();qc.invalidateQueries({queryKey:["inbox"]});}});
 useEffect(()=>{if(!selected&&q.data?.[0])setSelected(q.data[0].id)},[q.data,selected]);
 const active=q.data?.find(c=>c.id===activeId);
 return <><Header title="Unified Inbox" description="AI and human agents share one customer conversation workspace."/><div className="grid h-[calc(100vh-88px)] min-h-[620px] grid-cols-1 gap-4 p-4 lg:grid-cols-[360px_1fr]"><Card className="overflow-hidden"><CardHeader><CardTitle>Conversations</CardTitle></CardHeader><CardContent className="p-0"><div className="divide-y">{(q.data??[]).map(c=><button key={c.id} onClick={()=>setSelected(c.id)} className={`w-full p-4 text-left hover:bg-slate-50 ${activeId===c.id?"bg-brand-50":""}`}><div className="flex items-start justify-between gap-3"><div><p className="font-medium">{c.customer_name||"Anonymous customer"}</p><p className="mt-1 line-clamp-2 text-xs text-slate-500">{c.last_message||"No messages"}</p></div>{c.handoff_requested&&<span className="rounded-full bg-amber-100 px-2 py-1 text-[10px] font-semibold text-amber-700">HUMAN</span>}</div><p className="mt-2 text-[11px] text-slate-400">{c.message_count} messages · {c.channel_id.slice(0,8)}</p></button>)}{!q.isLoading&&(q.data??[]).length===0&&<div className="p-8 text-center text-sm text-slate-500">No customer conversations yet.</div>}</div></CardContent></Card><Card className="flex min-h-0 flex-col overflow-hidden"><CardHeader className="border-b"><div className="flex items-center justify-between gap-4"><div><CardTitle>{active?.customer_name||"Customer conversation"}</CardTitle><p className="mt-1 text-xs text-slate-500">{active?.customer_email||active?.customer_phone||"Anonymous customer"}</p></div>{active&&<Button size="sm" variant="outline" loading={handoff.isPending} onClick={()=>handoff.mutate({id:active.id,requested:!active.handoff_requested})}>{active.handoff_requested?<><UserRound className="h-4 w-4"/>Return to AI</>:"Take over"}</Button>}</div></CardHeader><CardContent className="flex min-h-0 flex-1 flex-col p-0"><div className="flex-1 space-y-3 overflow-y-auto p-5">{(messages.data??[]).map(m=><div key={m.id} className={`max-w-[78%] rounded-2xl px-4 py-3 text-sm ${m.role==="user"?"bg-slate-100 text-slate-800":m.role==="human"?"ml-auto bg-brand-600 text-white":"bg-brand-50 text-slate-800"}`}><div className="mb-1 text-[10px] font-semibold uppercase opacity-60">{m.role}</div>{m.content}</div>)}{active&&!messages.isLoading&&(messages.data??[]).length===0&&<div className="py-16 text-center text-sm text-slate-400">No messages yet.</div>}</div><div className="border-t p-4"><div className="flex gap-2"><Input value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey&&text.trim()&&activeId){e.preventDefault();send.mutate()}}} placeholder={active?.handoff_requested?"Reply as a human agent…":"Take over to reply to the customer…"} disabled={!activeId}/><Button disabled={!activeId||!text.trim()} loading={send.isPending} onClick={()=>send.mutate()}><Send className="h-4 w-4"/>Send</Button></div></div></CardContent></Card></div></>;
}
