"use client";

import Link from "next/link";
import { useQuery } from "@tanstack/react-query";
import { Bot, Plus } from "lucide-react";
import { listEmployees } from "@/lib/api";
import { Header } from "@/components/layout/header";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

export default function PlatformAIEmployeesPage(){const employees=useQuery({queryKey:["platform-internal-ai-employees"],queryFn:listEmployees});return <><Header title="Internal AI Employees" description="AI workforce used by the platform team for operations, HR, sales, marketing, finance, and support."/><div className="space-y-6 p-6"><Card><CardHeader className="flex flex-row items-center justify-between"><CardTitle>Platform AI workforce</CardTitle><Link href="/employees/new" className="inline-flex items-center gap-2 rounded-lg bg-brand-600 px-3 py-2 text-sm font-medium text-white"><Plus className="h-4 w-4"/>Create AI employee</Link></CardHeader><CardContent>{employees.isLoading?<p className="text-sm text-gray-500">Loading…</p>:employees.isError?<p className="text-sm text-red-600">Unable to load the internal AI workforce.</p>:<div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{(employees.data??[]).map(e=><Link key={e.id} href={`/employees/${e.id}`} className="rounded-lg border p-4 hover:bg-gray-50"><div className="flex items-center gap-2"><Bot className="h-4 w-4 text-brand-600"/><p className="font-medium">{e.name}</p></div><p className="mt-1 text-xs text-gray-500">{e.slug} · {e.kind}</p><p className="mt-3 text-xs">{e.is_active?"Active":"Disabled"}</p></Link>)}</div>}</CardContent></Card><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><RoleCard title="Operations AI" text="Monitors platform health, incidents, queues, and recurring operational work."/><RoleCard title="HR AI" text="Supports hiring pipelines, onboarding, policies, and internal people operations."/><RoleCard title="Sales & Marketing AI" text="Handles lead research, campaign operations, content, and pipeline assistance."/><RoleCard title="Finance AI" text="Supports billing review, reconciliation, reporting, and anomaly detection."/></div></div></>}
function RoleCard({title,text}:{title:string;text:string}){return <Card><CardContent className="p-5"><p className="font-semibold">{title}</p><p className="mt-1 text-sm text-gray-500">{text}</p></CardContent></Card>}
