"""Aggregate API v1 routers."""

from fastapi import APIRouter

from app.api.v1 import work_items, test_center, test_center_evidence, api_keys, admin, approvals, auth, employees, feedback, files, runs, usage, knowledge, memory, workflows, workflow_events, workflow_schedules, workflow_approvals, operations, customer_dashboard, billing, billing_webhooks, invoices, orders, sales, customer_channels, public_chat, products, commerce_integrations, onboarding, inbox, customers, channel_webhooks, sales_readiness, tenant_admin, reseller_admin, admin_providers, edition_control, license_control

api_router = APIRouter()
api_router.include_router(work_items.router)
api_router.include_router(test_center.router)
api_router.include_router(test_center_evidence.router)
api_router.include_router(auth.router)
api_router.include_router(api_keys.router)
api_router.include_router(admin.router)
api_router.include_router(admin_providers.router)
api_router.include_router(edition_control.router)
api_router.include_router(license_control.router)
api_router.include_router(files.router)
api_router.include_router(employees.router)
api_router.include_router(runs.router)
api_router.include_router(usage.router)
api_router.include_router(billing.router)
api_router.include_router(billing_webhooks.router)
api_router.include_router(approvals.router)
api_router.include_router(feedback.router)
api_router.include_router(knowledge.router)
api_router.include_router(memory.router)
api_router.include_router(workflows.router)
api_router.include_router(workflow_schedules.router)
api_router.include_router(workflow_events.router)
api_router.include_router(workflow_approvals.router)
api_router.include_router(operations.router)
api_router.include_router(customer_dashboard.router)
api_router.include_router(invoices.router)
api_router.include_router(orders.router)
api_router.include_router(sales.router)
api_router.include_router(customer_channels.router)
api_router.include_router(public_chat.router)
api_router.include_router(products.router)
api_router.include_router(commerce_integrations.router)
api_router.include_router(onboarding.router)
api_router.include_router(inbox.router)
api_router.include_router(customers.router)
api_router.include_router(channel_webhooks.router)
api_router.include_router(sales_readiness.router)
api_router.include_router(tenant_admin.router)
api_router.include_router(reseller_admin.router)
