"use client";

import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Header } from "@/components/layout/header";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Spinner } from "@/components/ui/spinner";
import { createCustomerChannel, listCustomerChannels, listEmployees, getErrorMessage } from "@/lib/api";
import { Bot, Check, Copy, ExternalLink, Globe2, MessageCircle, Plus, Radio, X } from "lucide-react";

export default function ChannelsPage() {
  const qc = useQueryClient(); const [open, setOpen] = useState(false); const [employeeId, setEmployeeId] = useState("");
  const [name, setName] = useState("Website Sales Assistant"); const [webhookSecret, setWebhookSecret] = useState(""); const [type, setType] = useState<"web_widget" | "public_chat" | "whatsapp">("web_widget"); const [copied, setCopied] = useState<string | null>(null);
  const employeesQ = useQuery({ queryKey: ["employees"], queryFn: listEmployees }); const channelsQ = useQuery({ queryKey: ["customer-channels"], queryFn: () => listCustomerChannels() });
  const create = useMutation({ mutationFn: () => createCustomerChannel({ employee_id: employeeId, name, channel_type: type, config: type === "whatsapp" && webhookSecret ? { webhook_secret: webhookSecret } : {} }), onSuccess: () => { qc.invalidateQueries({ queryKey: ["customer-channels"] }); setOpen(false); setName("Website Sales Assistant"); setWebhookSecret(""); } });
  const employees = useMemo(() => employeesQ.data ?? [], [employeesQ.data]); const channels = channelsQ.data ?? []; const origin = typeof window !== "undefined" ? window.location.origin : "";
  const employeeName = useMemo(() => employees.find(e => e.id === employeeId)?.name ?? "", [employees, employeeId]);
  async function copy(value: string) { await navigator.clipboard.writeText(value); setCopied(value); window.setTimeout(() => setCopied(null), 1400); }
  return <>
    <Header title="Customer Channels" description="Publish your AI Employees where your customers already are." actions={<Button size="sm" onClick={() => setOpen(true)}><Plus className="h-4 w-4" />New channel</Button>} />
    <div className="space-y-6 p-6">
      <Card className="overflow-hidden border-brand-100 bg-gradient-to-br from-brand-50 to-white"><CardContent className="grid gap-5 p-6 md:grid-cols-[1fr_auto] md:items-center"><div><div className="mb-2 flex items-center gap-2 text-brand-700"><Radio className="h-4 w-4" /><span className="text-xs font-semibold uppercase tracking-wider">Customer Experience</span></div><h2 className="text-xl font-semibold text-slate-900">Turn an AI Employee into a customer-facing sales assistant.</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-600">Create a public chat link for campaigns and QR codes, or install the floating widget on your store website. Customers never need a SaaS account.</p></div><div className="flex gap-3"><div className="rounded-xl bg-white p-4 text-center shadow-sm ring-1 ring-slate-200"><Globe2 className="mx-auto h-5 w-5 text-brand-600" /><p className="mt-1 text-xs font-medium">Web</p></div><div className="rounded-xl bg-white p-4 text-center shadow-sm ring-1 ring-slate-200"><MessageCircle className="mx-auto h-5 w-5 text-brand-600" /><p className="mt-1 text-xs font-medium">Chat</p></div></div></CardContent></Card>
      {channelsQ.isLoading && <Spinner />}{channelsQ.error && <div className="rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{getErrorMessage(channelsQ.error)}</div>}
      {!channelsQ.isLoading && !channelsQ.error && channels.length === 0 && <Card><CardContent className="flex flex-col items-center p-12 text-center"><Radio className="h-9 w-9 text-slate-300" /><h3 className="mt-4 font-semibold text-slate-900">No customer channels yet</h3><p className="mt-1 max-w-md text-sm text-slate-500">Publish your first employee to get a shareable customer chat and website widget.</p><Button className="mt-5" size="sm" onClick={() => setOpen(true)}><Plus className="h-4 w-4" />Create channel</Button></CardContent></Card>}
      <div className="grid gap-4 lg:grid-cols-2">
        {channels.map((channel) => {
          const chatUrl = `${origin}/chat/${channel.public_key}`;
          const embed = `<script src="${origin}/widget.js?channel=${channel.public_key}"></script>`;
          const webhook = `${origin}/api/v1/webhooks/channels/whatsapp/${channel.id}`;
          const label = channel.channel_type === "web_widget" ? "Website widget" : channel.channel_type === "whatsapp" ? "WhatsApp" : "Public chat";
          return <Card key={channel.id}>
            <CardHeader className="flex flex-row items-start justify-between gap-4">
              <div className="flex items-start gap-3"><div className="rounded-lg bg-brand-50 p-2.5"><Bot className="h-5 w-5 text-brand-600" /></div><div><CardTitle className="text-base">{channel.name}</CardTitle><p className="mt-1 text-xs text-slate-500">{employees.find(e => e.id === channel.employee_id)?.name ?? "AI Employee"} · {label}</p></div></div>
              <Badge status={channel.is_active ? "active" : "inactive"} />
            </CardHeader>
            <CardContent className="space-y-4">
              <div><p className="mb-1.5 text-xs font-semibold uppercase tracking-wide text-slate-400">Customer chat URL</p><div className="flex gap-2"><input readOnly value={chatUrl} className="min-w-0 flex-1 rounded-lg border border-slate-200 bg-slate-50 px-3 py-2 text-xs text-slate-600" /><Button size="sm" variant="outline" onClick={() => copy(chatUrl)}>{copied === chatUrl ? <Check className="h-4 w-4" /> : <Copy className="h-4 w-4" />}</Button><a href={chatUrl} target="_blank" rel="noreferrer" className="inline-flex h-9 items-center rounded-lg border border-slate-200 px-3 text-slate-600 hover:bg-slate-50"><ExternalLink className="h-4 w-4" /></a></div></div>
              {channel.channel_type === "whatsapp" ? <div><p className="mb-1.5 text-xs font-semibold uppercase tracking-wide text-slate-400">WhatsApp webhook</p><div className="flex gap-2"><code className="min-w-0 flex-1 overflow-hidden rounded-lg bg-slate-950 px-3 py-2 text-[11px] text-slate-200">{webhook}</code><Button size="sm" variant="outline" onClick={() => copy(webhook)}>{copied === webhook ? <Check className="h-4 w-4" /> : <Copy className="h-4 w-4" />}</Button></div><p className="mt-2 text-xs text-slate-500">Provider-neutral inbound endpoint. Connect your WhatsApp Business provider/webhook adapter to this endpoint.</p></div> : <div><p className="mb-1.5 text-xs font-semibold uppercase tracking-wide text-slate-400">Website embed</p><div className="flex gap-2"><code className="min-w-0 flex-1 overflow-hidden rounded-lg bg-slate-950 px-3 py-2 text-[11px] text-slate-200">{embed}</code><Button size="sm" variant="outline" onClick={() => copy(embed)}>{copied === embed ? <Check className="h-4 w-4" /> : <Copy className="h-4 w-4" />}</Button></div></div>}
            </CardContent>
          </Card>;
        })}
      </div>
    </div>
    {open && <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/40 p-4" onMouseDown={(e) => { if (e.target === e.currentTarget) setOpen(false); }}><Card className="w-full max-w-lg shadow-2xl"><CardHeader className="flex flex-row items-center justify-between"><div><CardTitle>Publish customer channel</CardTitle><p className="mt-1 text-sm text-slate-500">Choose which AI Employee your customers will talk to.</p></div><button onClick={() => setOpen(false)} className="rounded-lg p-2 text-slate-400 hover:bg-slate-100"><X className="h-5 w-5" /></button></CardHeader><CardContent className="space-y-4"><label className="block"><span className="mb-1.5 block text-sm font-medium text-slate-700">AI Employee</span><select value={employeeId} onChange={e => setEmployeeId(e.target.value)} className="w-full rounded-lg border border-slate-300 px-3 py-2.5 text-sm"><option value="">Select an employee…</option>{employees.map(e => <option key={e.id} value={e.id}>{e.name} · {e.kind}</option>)}</select></label><label className="block"><span className="mb-1.5 block text-sm font-medium text-slate-700">Channel name</span><input value={name} onChange={e => setName(e.target.value)} className="w-full rounded-lg border border-slate-300 px-3 py-2.5 text-sm" placeholder="Website Sales Assistant" /></label><label className="block"><span className="mb-1.5 block text-sm font-medium text-slate-700">WhatsApp webhook secret <span className="font-normal text-slate-400">(optional)</span></span><input type="password" value={webhookSecret} onChange={e => setWebhookSecret(e.target.value)} disabled={type !== "whatsapp"} className="w-full rounded-lg border border-slate-300 px-3 py-2.5 text-sm disabled:bg-slate-50" placeholder="Shared secret for provider adapter" /></label><div><span className="mb-1.5 block text-sm font-medium text-slate-700">Experience</span><div className="grid grid-cols-3 gap-3">{(["web_widget", "public_chat", "whatsapp"] as const).map(v => <button type="button" key={v} onClick={() => setType(v)} className={`rounded-xl border p-3 text-left ${type === v ? "border-brand-500 bg-brand-50" : "border-slate-200 hover:bg-slate-50"}`}><p className="text-sm font-medium">{v === "web_widget" ? "Website widget" : v === "whatsapp" ? "WhatsApp" : "Public chat"}</p><p className="mt-1 text-xs text-slate-500">{v === "web_widget" ? "Floating chat on your website" : v === "whatsapp" ? "Connect a WhatsApp Business provider" : "Shareable page / QR code"}</p></button>)}</div></div>{create.error && <p className="text-sm text-red-600">{getErrorMessage(create.error)}</p>}<Button className="w-full" disabled={!employeeId || !name.trim() || !employeeName} loading={create.isPending} onClick={() => create.mutate()}>Publish channel</Button></CardContent></Card></div>}
  </>;
}
