"use client";
import { Header } from "@/components/layout/header";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Bot, BookOpen, Brain, MessageCircle, Workflow, Code2, ArrowRight, Sparkles, Radio } from "lucide-react";
import Link from "next/link";
import { useI18n } from "@/lib/i18n/provider";
export default function AIWorkspacePage() {
 const {t}=useI18n(); const m=t.customerLegacy.workspace;
 const items=[{href:"/employees",title:m.employees,text:m.employeesText,icon:Bot},{href:"/conversations",title:m.conversations,text:m.conversationsText,icon:MessageCircle},{href:"/knowledge",title:m.knowledge,text:m.knowledgeText,icon:BookOpen},{href:"/memory",title:m.memory,text:m.memoryText,icon:Brain},{href:"/workflows",title:m.workflows,text:m.workflowsText,icon:Workflow},{href:"/channels",title:m.channels,text:m.channelsText,icon:Radio},{href:"/developer",title:m.developer,text:m.developerText,icon:Code2}];
 return <><Header title={m.title} description={m.description}/><div className="space-y-6 p-6" dir="auto"><Card className="overflow-hidden border-brand-100 bg-brand-50/50"><CardContent className="flex flex-col gap-5 p-6 md:flex-row md:items-center md:justify-between"><div className="flex items-start gap-4"><div className="rounded-xl bg-brand-600 p-3 text-white"><Sparkles className="h-6 w-6"/></div><div><p className="text-lg font-semibold text-gray-900">{m.hero}</p><p className="mt-1 max-w-2xl text-sm text-gray-600">{m.heroText}</p></div></div><Link href="/employees/new" className="inline-flex shrink-0 items-center justify-center gap-2 rounded-lg bg-brand-600 px-4 py-2.5 text-sm font-medium text-white hover:bg-brand-700">{m.create}<ArrowRight className="h-4 w-4"/></Link></CardContent></Card><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{items.map(({href,title,text,icon:Icon})=><Link key={href} href={href} className="group"><Card className="h-full transition group-hover:-translate-y-0.5 group-hover:border-brand-200 group-hover:shadow-sm"><CardHeader className="flex flex-row items-center gap-3 pb-2"><div className="rounded-lg bg-brand-50 p-2.5 text-brand-600"><Icon className="h-5 w-5"/></div><CardTitle className="text-base">{title}</CardTitle></CardHeader><CardContent><p className="text-sm leading-6 text-gray-500">{text}</p><p className="mt-4 text-sm font-medium text-brand-600">{m.open} →</p></CardContent></Card></Link>)}</div></div></>;
}
