from app.shared.events import DomainEvent
from app.shared.event_catalog import (
    ORDER_COMPLETED, ORDER_CANCELLED, INVOICE_ISSUED,
    PAYMENT_SUCCEEDED, CUSTOMER_CREATED, DOCUMENT_INGESTED,
    WORKFLOW_RUN_COMPLETED, EMPLOYEE_RUN_COMPLETED,
)
