from typing import Any, Protocol

class PaymentGateway(Protocol):
    async def create_customer(self, *, tenant_id: str, email: str | None = None) -> str: ...
    async def create_checkout(self, *, customer_id: str, plan_id: str) -> str: ...

class CommerceProvider(Protocol):
    async def list_orders(self, *, tenant_id: str, cursor: str | None = None) -> list[dict[str, Any]]: ...

class AIProvider(Protocol):
    async def generate(self, *, messages: list[dict[str, Any]], model: str, **kwargs: Any) -> Any: ...
