from typing import Any, Generic, Protocol, TypeVar
EntityT = TypeVar("EntityT")
IdT = TypeVar("IdT")

class Repository(Protocol, Generic[EntityT, IdT]):
    async def get(self, entity_id: IdT) -> EntityT | None: ...
    async def add(self, entity: EntityT) -> EntityT: ...
    async def update(self, entity: EntityT) -> EntityT: ...
    async def delete(self, entity_id: IdT) -> None: ...

class UnitOfWork(Protocol):
    async def __aenter__(self) -> "UnitOfWork": ...
    async def __aexit__(self, exc_type: Any, exc: Any, tb: Any) -> None: ...
    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...
