from typing import BinaryIO, Protocol

class ObjectStorage(Protocol):
    async def put(self, key: str, stream: BinaryIO, *, content_type: str | None = None) -> str: ...
    async def get(self, key: str) -> BinaryIO: ...
    async def delete(self, key: str) -> None: ...
