"use client";

import { useState, type ReactNode } from "react";
import { useMutation, useQuery } from "@tanstack/react-query";
import { Header } from "@/components/layout/header";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Spinner } from "@/components/ui/spinner";
import { createEmployee, getErrorMessage, listAvailableTools, listEmployees } from "@/lib/api";
import { Bot, Check, Code2, Save, ShieldCheck, SlidersHorizontal, Wrench } from "lucide-react";
import { useI18n } from "@/lib/i18n/provider";

export default function StudioPage() {
  const { t } = useI18n();
  const m = t.studio;
  const employees = useQuery({ queryKey: ["employees"], queryFn: listEmployees });
  const tools = useQuery({ queryKey: ["available-tools"], queryFn: listAvailableTools });
  const [name,set{m.name}]=useState(""); const [slug,set{m.slug}]=useState(""); const [kind,set{m.kind}]=useState("assistant"); const [prompt,setPrompt]=useState("You are a reliable AI employee. Complete the user's task accurately and explain important decisions."); const [selectedTools,setSelectedTools]=useState<string[]>([]); const [autonomy,setAutonomy]=useState(true); const [maxSteps,setMaxSteps]=useState(6); const [requirePlan,setRequirePlan]=useState(true); const [outputSchema,setOutputSchema]=useState('{\n  "result": "string"\n}');
  const create = useMutation({ mutationFn: () => createEmployee({ slug: slug.trim(), name: name.trim(), kind, prompt_template: prompt, allowed_tools: selectedTools, output_schema: JSON.parse(outputSchema), rules: { autonomy: { enabled: autonomy, max_steps: maxSteps, require_plan: requirePlan }, memory: { enabled: true, auto_extract: true, query_fields: ["message"] } } }), onSuccess: () => employees.refetch() });
  const existing = employees.data ?? [];
  const toggle = (n:string) => setSelectedTools(v => v.includes(n) ? v.filter(x=>x!==n) : [...v,n]);
  const invalid = !name.trim() || !slug.trim() || !prompt.trim() || create.isPending;
  return <>
    <Header title={m.title} description={m.description} />
    <div class{m.name}="grid gap-6 p-6 xl:grid-cols-[minmax(0,1fr)_360px]">
      <div class{m.name}="space-y-6">
        <Card><CardHeader><CardTitle class{m.name}="flex items-center gap-2"><Bot class{m.name}="h-4 w-4 text-brand-600"/>{m.employeeDefinition}</CardTitle></CardHeader><CardContent class{m.name}="grid gap-4 sm:grid-cols-2"><Field label="{m.name}"><input value={name} onChange={e=>set{m.name}(e.target.value)} placeholder="{m.namePlaceholder}"/></Field><Field label="{m.slug}"><input value={slug} onChange={e=>set{m.slug}(e.target.value)} placeholder="{m.slugPlaceholder}"/></Field><Field label="{m.kind}"><select value={kind} onChange={e=>set{m.kind}(e.target.value)}><option>assistant</option><option>analyst</option><option>sales</option><option>operations</option><option>support</option></select></Field><div class{m.name}="rounded-xl bg-gray-50 p-4 text-sm"><p class{m.name}="font-medium text-gray-800">{m.runtime}</p><p class{m.name}="mt-1 text-xs text-gray-500">{m.runtimeDescription}</p></div></CardContent></Card>
        <Card><CardHeader><CardTitle>{m.systemPrompt}</CardTitle></CardHeader><CardContent><textarea value={prompt} onChange={e=>setPrompt(e.target.value)} rows={9} class{m.name}="w-full rounded-xl border border-gray-300 p-3 font-mono text-sm"/><div class{m.name}="mt-3 flex flex-wrap gap-2"><Badge>{m.memoryAware}</Badge><Badge>{m.toolAware}</Badge><Badge>{m.tenantScoped}</Badge></div></CardContent></Card>
        <Card><CardHeader><CardTitle class{m.name}="flex items-center gap-2"><Wrench class{m.name}="h-4 w-4 text-brand-600"/>{m.allowedTools}</CardTitle></CardHeader><CardContent><div class{m.name}="grid gap-3 sm:grid-cols-2">{tools.isLoading ? <Spinner/> : (tools.data ?? []).map(t => <button key={t.name} onClick={()=>toggle(t.name)} class{m.name}={`rounded-xl border p-4 text-left transition ${selectedTools.includes(t.name)?"border-brand-400 bg-brand-50":"border-gray-200 hover:bg-gray-50"}`}><div class{m.name}="flex items-center justify-between gap-2"><span class{m.name}="font-medium text-sm">{t.name}</span>{selectedTools.includes(t.name)&&<Check class{m.name}="h-4 w-4 text-brand-600"/>}</div><p class{m.name}="mt-1 text-xs text-gray-500">{t.description}</p><p class{m.name}="mt-2 text-[11px] text-gray-400">{t.side_effects?"{m.sideEffect}":"{m.safeTool}"}</p></button>)}{!(tools.data ?? []).length && <p class{m.name}="text-sm text-gray-500">{m.noTools}</p>}</div></CardContent></Card>
        <Card><CardHeader><CardTitle class{m.name}="flex items-center gap-2"><SlidersHorizontal class{m.name}="h-4 w-4 text-brand-600"/>{m.autonomyMemory}</CardTitle></CardHeader><CardContent class{m.name}="space-y-5"><Toggle label="{m.autonomousPlanning}" description="{m.autonomousPlanningDescription}" value={autonomy} onChange={setAutonomy}/><Toggle label="{m.requirePlan}" description="{m.requirePlanDescription}" value={requirePlan} onChange={setRequirePlan}/><Toggle label="{m.autoMemory}" description="{m.autoMemoryDescription}" value={true} onChange={()=>{}} disabled/><div><label class{m.name}="text-sm font-medium">{m.maxPlanSteps} <span class{m.name}="text-gray-400">({maxSteps})</span></label><input type="range" min="1" max="20" value={maxSteps} onChange={e=>setMaxSteps(Number(e.target.value))} class{m.name}="mt-3 w-full"/></div></CardContent></Card>
        <Card><CardHeader><CardTitle class{m.name}="flex items-center gap-2"><Code2 class{m.name}="h-4 w-4"/>{m.outputSchema}</CardTitle></CardHeader><CardContent><textarea value={outputSchema} onChange={e=>setOutputSchema(e.target.value)} rows={7} class{m.name}="w-full rounded-xl border border-gray-300 p-3 font-mono text-xs"/></CardContent></Card>
        <div class{m.name}="flex flex-wrap items-center gap-3"><Button disabled={invalid} onClick={()=>create.mutate()}><Save class{m.name}="h-4 w-4"/>{create.isPending?"{m.creating}":"{m.create}"}</Button>{create.error&&<span class{m.name}="text-sm text-red-600">{getErrorMessage(create.error)}</span>}{create.isSuccess&&<span class{m.name}="text-sm text-emerald-600">{m.createdSuccess}</span>}</div>
      </div>
      <div class{m.name}="space-y-6"><Card><CardHeader><CardTitle>{m.currentEmployees}</CardTitle></CardHeader><CardContent class{m.name}="space-y-2">{existing.slice(0,8).map(e=><div key={e.id} class{m.name}="flex items-center justify-between rounded-lg bg-gray-50 p-3"><div><p class{m.name}="text-sm font-medium">{e.name}</p><p class{m.name}="text-xs text-gray-500">{e.kind}</p></div><Badge status={e.is_active?"active":"inactive"}/></div>)}{!existing.length&&<p class{m.name}="text-sm text-gray-500">{m.createFirst}</p>}</CardContent></Card><Card><CardHeader><CardTitle class{m.name}="flex items-center gap-2"><ShieldCheck class{m.name}="h-4 w-4 text-brand-600"/>{m.safetyBoundary}</CardTitle></CardHeader><CardContent class{m.name}="space-y-3 text-sm text-gray-600"><p>{m.toolPermissions}</p><p>{m.sideEffectPolicy}</p><p>{m.autonomousPlanning} cannot bypass RBAC or tenant isolation.</p></CardContent></Card></div>
    </div>
  </>;
}
function Field({label,children}:{label:string;children:ReactNode}){return <label class{m.name}="text-sm font-medium text-gray-700">{label}<div class{m.name}="mt-1.5">{children}</div></label>}
function Toggle({label,description,value,onChange,disabled=false}:{label:string;description:string;value:boolean;onChange:(v:boolean)=>void;disabled?:boolean}){return <button type="button" disabled={disabled} onClick={()=>onChange(!value)} class{m.name}="flex w-full items-start justify-between gap-4 rounded-xl border border-gray-200 p-4 text-left disabled:opacity-60"><span><span class{m.name}="block text-sm font-medium text-gray-900">{label}</span><span class{m.name}="mt-1 block text-xs leading-5 text-gray-500">{description}</span></span><span class{m.name}={`mt-0.5 flex h-6 w-11 shrink-0 rounded-full p-1 transition ${value?"bg-brand-600":"bg-gray-200"}`}><span class{m.name}={`h-4 w-4 rounded-full bg-white shadow transition ${value?"translate-x-5":"translate-x-0"}`}/></span></button>}
